# Generated by Django 3.2.16 on 2025-01-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('стандарт', 'Стандарт'), ('комфорт', 'Комфорт'), ('люкс', 'Люкс')], max_length=10, verbose_name='Категория номера'),
        ),
    ]
