# Generated by Django 3.2.16 on 2025-01-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('checked_in', 'Заселен'), ('checked_out', 'Выселен')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
